name: Smart Contract CI

# Gatilhos: Roda o pipeline a cada push ou pull request na branch 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-dev gcc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eth-brownie

      - name: Install Solidity dependencies
        run: brownie pm install OpenZeppelin/openzeppelin-contracts@4.9.3

      - name: Run tests
        run: brownie test
